version: 0.2

env:
  variables:
    SOLUTION: .\CodeBuildTest.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6

phases:
  build:
    commands:
      - '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride=".\v4.6" $env:SOLUTION'

artifacts:
  files:
    - .\CodeBuildTest\bin\*
    
    
    